name: Run Unit Tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore src/chronos.sln
    
    - name: Build
      run: dotnet build src/chronos.sln --no-restore
    
    - name: Test
      run: dotnet test src/chronos.sln --no-build --verbosity normal
